---
# tasks file for timesyncd
- name: Install systemd-timesyncd package
  ansible.builtin.package:
    name: systemd-timesyncd
    state: present

- name: Get systemd version
  ansible.builtin.command: systemctl --version
  register: systemctl_version
  changed_when: false
  check_mode: false

- name: Set systemd version fact
  ansible.builtin.set_fact:
    systemd_version: "{{ systemctl_version.stdout_lines[0][8:11] }}"

- name: Configure timesyncd
  ansible.builtin.template:
    src: etc/systemd/timesyncd.conf.j2
    dest: /etc/systemd/timesyncd.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart and enable timesyncd
